# Colours from the original ab-hive-mind palette
# See http://colorbrewer2.org/?type=qualitative&scheme=Pastel1&n=8
# We just use primaries for easy ID

[[device]]
id = "nefario"
bt_name = "Dr Nefario"
colour = [0xFF, 0x00, 0x00]

[[device]]
id = "strange"
bt_name = "Dr Strange"
colour = [0x00, 0xFF, 0x00]

[[device]]
id = "who"
bt_name = "Dr Who"
colour = [0x00, 0x00, 0xFF]
